# Generated by Django 4.0.4 on 2022-09-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tc',
        ),
    ]
